// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4XIptjnT8zQMLAtm_FzYnQljUykl4XPg',
    appId: '1:737326598104:web:6720dcd4f659d95dcf14ad',
    messagingSenderId: '737326598104',
    projectId: 'blog-78b55',
    authDomain: 'blog-78b55.firebaseapp.com',
    storageBucket: 'blog-78b55.appspot.com',
    measurementId: 'G-CHKV4XYM8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHC8H54Y9x82dW6ug1y5usTEcv7r7b858',
    appId: '1:737326598104:android:a1d411dd959ab541cf14ad',
    messagingSenderId: '737326598104',
    projectId: 'blog-78b55',
    storageBucket: 'blog-78b55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUnc51BZvlivB_hjyaH3Ub6u_j6NlZIYE',
    appId: '1:737326598104:ios:3d13ef84104fc324cf14ad',
    messagingSenderId: '737326598104',
    projectId: 'blog-78b55',
    storageBucket: 'blog-78b55.appspot.com',
    androidClientId: '737326598104-49b9gqj8e798u86qkjqiq4vt877tg6tf.apps.googleusercontent.com',
    iosClientId: '737326598104-6k392kbs8ckl1vovjmb8elbvnsg3es2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduleMeeting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUnc51BZvlivB_hjyaH3Ub6u_j6NlZIYE',
    appId: '1:737326598104:ios:3d13ef84104fc324cf14ad',
    messagingSenderId: '737326598104',
    projectId: 'blog-78b55',
    storageBucket: 'blog-78b55.appspot.com',
    androidClientId: '737326598104-49b9gqj8e798u86qkjqiq4vt877tg6tf.apps.googleusercontent.com',
    iosClientId: '737326598104-6k392kbs8ckl1vovjmb8elbvnsg3es2u.apps.googleusercontent.com',
    iosBundleId: 'com.example.scheduleMeeting',
  );
}
