// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCySkEG3Wj_fxqe6ERabEPmjN1jId3ws',
    appId: '1:166533816328:web:2a4b3bdc526048de42b1bd',
    messagingSenderId: '166533816328',
    projectId: 'custom-map-f8b3a',
    authDomain: 'custom-map-f8b3a.firebaseapp.com',
    storageBucket: 'custom-map-f8b3a.appspot.com',
    measurementId: 'G-XLSQCTQHQ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3BWYyKbll9IdrmUlYafaRq2V56oe7fco',
    appId: '1:166533816328:android:e44a1e82ecea4e9942b1bd',
    messagingSenderId: '166533816328',
    projectId: 'custom-map-f8b3a',
    storageBucket: 'custom-map-f8b3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLa0aoo11sP3DPKsR8QKL0XM-kGiPSiw',
    appId: '1:166533816328:ios:54acb8751ae4c7a742b1bd',
    messagingSenderId: '166533816328',
    projectId: 'custom-map-f8b3a',
    storageBucket: 'custom-map-f8b3a.appspot.com',
    iosClientId: '166533816328-06vk8he88s9qnea5hr7r2kd4ugsfu8ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBLa0aoo11sP3DPKsR8QKL0XM-kGiPSiw',
    appId: '1:166533816328:ios:54acb8751ae4c7a742b1bd',
    messagingSenderId: '166533816328',
    projectId: 'custom-map-f8b3a',
    storageBucket: 'custom-map-f8b3a.appspot.com',
    iosClientId: '166533816328-06vk8he88s9qnea5hr7r2kd4ugsfu8ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.myWallet',
  );
}
